# Generated by Django 4.1.13 on 2024-11-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessclass",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
