# Generated by Django 4.1.13 on 2024-12-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessclass",
            name="capacity",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="fitnessclass",
            name="location",
            field=models.CharField(default=30, max_length=100),
            preserve_default=False,
        ),
    ]
