# Generated by Django 4.1.13 on 2024-11-08 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_alter_fitnessclass_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessclass",
            name="time",
        ),
    ]
