# Generated by Django 4.1.13 on 2024-12-09 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0003_alter_fitnessclass_table_alter_userclass_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="fitnessclass",
            table=None,
        ),
        migrations.AlterModelTable(
            name="userclass",
            table=None,
        ),
    ]
