# Generated by Django 4.1.13 on 2024-11-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_fitnessclass_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
