# Generated by Django 4.1.13 on 2024-12-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_description_post_content_remove_post_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
