# Generated by Django 4.1.13 on 2024-12-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
