# Generated by Django 4.1.13 on 2024-12-09 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0009_alter_comment_table_alter_commentlike_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="commentlike",
            table=None,
        ),
        migrations.AlterModelTable(
            name="like",
            table=None,
        ),
        migrations.AlterModelTable(
            name="post",
            table=None,
        ),
    ]
