# Generated by Django 4.1.13 on 2024-11-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "measurements",
            "0002_alter_measurement_calves_alter_measurement_chest_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={},
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="date",
        ),
        migrations.AlterField(
            model_name="measurement",
            name="calves",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="chest",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="hips",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="left_arm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="notes",
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="right_arm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="thighs",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="unit",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="waist",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterModelTable(
            name="measurement",
            table="measurements_measurement",
        ),
    ]
