# Generated by Django 4.1.13 on 2024-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0004_measurement_date_alter_measurement_calves_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="bmi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
