# Generated by Django 4.1.13 on 2024-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0005_measurement_bmi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="calves",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="chest",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="hips",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="left_arm",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="right_arm",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="thighs",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measurement",
            name="waist",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
    ]
