# Generated by Django 4.1.13 on 2024-12-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workout',
            table='workouts',
        ),
    ]
