# Generated by Django 4.1.13 on 2024-12-09 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0002_alter_workout_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="workout",
            table=None,
        ),
    ]
